# Generated by Django 4.0.4 on 2022-05-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textmessages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
